name: test_flutter
description: A Flutter example package for testing and publishing to pub.dev
version: 1.0.0
homepage: https://github.com/yourusername/test-flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
